JAVA ?= $(or $(wildcard /opt/homebrew/opt/openjdk/bin/java),java)
GDK ?= $(HOME)/mars/m68k-elf
.DEFAULT_GOAL := all
.PHONY: all assets check-rom test references clean
all: check-rom
	$(MAKE) assets
	$(MAKE) -f $(GDK)/makefile.gen JAVA=$(JAVA) LIBGCC="$(shell $(GDK)/bin/m68k-elf-gcc -m68000 -print-libgcc-file-name)"
	python3 tools/finalize_rom.py out/release/rom.bin
check-rom:
	@python3 tools/arcade_source.py
.venv/.requirements-installed: requirements.txt
	@test -x .venv/bin/python || python3 -m venv .venv
	.venv/bin/python -m pip install -r requirements.txt
	@touch $@
assets: check-rom .venv/.requirements-installed
	.venv/bin/python tools/build_assets.py
references: all
	.venv/bin/python tools/prepare_source_data.py --all
test: all
	.venv/bin/python tests/test_source_only.py
	.venv/bin/python tools/prepare_source_data.py --all
	.venv/bin/python tests/test_pots.py
	.venv/bin/python tests/test_pots_runtime.py
	.venv/bin/python tests/test_pot_placements_runtime.py
	.venv/bin/python tests/test_boss_hud_runtime.py
	.venv/bin/python tests/test_menu_shop_poison_runtime.py
	.venv/bin/python tests/test_dragon_colors_runtime.py
	.venv/bin/python tests/test_arcade_coin_runtime.py
	.venv/bin/python tests/test_review_fixes_runtime.py
	.venv/bin/python tests/test_cadence_stats.py
	.venv/bin/python tests/test_animation_step.py
	.venv/bin/python tests/test_terrain_strips.py
	.venv/bin/python tests/test_weapon_contact_batch.py
	.venv/bin/python tests/test_encounter_pacing.py
	.venv/bin/python tests/test_level_select_runtime.py
	.venv/bin/python tests/test_debug_runtime.py
	.venv/bin/python tests/test_debug_unlock_runtime.py
	.venv/bin/python tests/test_level2_routes_runtime.py
	.venv/bin/python tests/test_level3_corridor_runtime.py
	.venv/bin/python tests/test_horizontal_wrap_runtime.py
	.venv/bin/python tests/test_level4_original_runtime.py
	.venv/bin/python tests/test_level5_parallax_runtime.py
	.venv/bin/python tests/test_level5_columns_runtime.py
	.venv/bin/python tests/test_level6_original_runtime.py
	.venv/bin/python tests/test_level6_wall_runtime.py
	.venv/bin/python tests/test_level6_sign_colors.py
	.venv/bin/python tests/test_level7_windows_runtime.py
	.venv/bin/python tests/test_level7_jump_assist_runtime.py
	.venv/bin/python tests/test_background_art_runtime.py
	.venv/bin/python tests/test_scenery_fixes_runtime.py
	.venv/bin/python tests/test_palace_debug_runtime.py
	.venv/bin/python tests/test_palace_composition_runtime.py
	.venv/bin/python tests/test_backdrop_runtime.py
	.venv/bin/python tests/test_home_logo_runtime.py
	.venv/bin/python tests/test_arena_parallax_runtime.py
	.venv/bin/python tests/test_boot_logos_runtime.py
	.venv/bin/python tests/test_hud_runtime.py
	.venv/bin/python tests/test_settings_runtime.py
	.venv/bin/python tests/test_frontend_runtime.py
	.venv/bin/python tests/test_high_score_runtime.py
	.venv/bin/python tests/test_high_score_table_runtime.py
	.venv/bin/python tests/test_v15_shop_dialogue_runtime.py
	.venv/bin/python tests/test_boss_rush_runtime.py
	.venv/bin/python tests/test_presentation_runtime.py
	.venv/bin/python tests/test_sfx.py
	.venv/bin/python tests/test_sfx_runtime.py
	.venv/bin/python tests/test_ending.py
	.venv/bin/python tests/test_ending_runtime.py
	.venv/bin/python tests/test_clear_screen_runtime.py
	.venv/bin/python tests/test_controls_runtime.py
	.venv/bin/python tests/test_actor_dispatch.py
	.venv/bin/python tests/test_background_runtime.py
	.venv/bin/python tests/test_bonus.py
	.venv/bin/python tests/test_bonus_runtime.py
	.venv/bin/python tests/test_music_catalog_runtime.py
	.venv/bin/python tests/test_music_events_runtime.py
	.venv/bin/python tests/test_music.py
	.venv/bin/python tests/test_music_runtime.py
	.venv/bin/python tests/test_frame_scheduler.py
	.venv/bin/python tests/test_frame_pacing.py
	.venv/bin/python tests/test_scroll_catchup_runtime.py
	.venv/bin/python tools/profile_runtime.py
	.venv/bin/python tools/profile_all_levels.py
	.venv/bin/python tests/test_armor_break.py
	.venv/bin/python tests/test_armor_break_runtime.py
	.venv/bin/python tests/test_game_over.py
	.venv/bin/python tests/test_game_over_runtime.py
	.venv/bin/python tests/test_round_clear.py
	.venv/bin/python tests/test_round_clear_runtime.py
	.venv/bin/python tests/test_player_death.py
	.venv/bin/python tests/test_player_death_runtime.py
	.venv/bin/python tests/test_posture_runtime.py
	.venv/bin/python tests/test_player_weapon_runtime.py
	.venv/bin/python tests/test_chain_actor.py
	.venv/bin/python tests/test_player_dagger.py
	.venv/bin/python tests/test_player_motion.py
	.venv/bin/python tests/test_player_motion_runtime.py
	.venv/bin/python tests/test_assets.py
	.venv/bin/python tests/test_runtime.py
	.venv/bin/python tools/check_sprite_render.py
	.venv/bin/python tests/test_large_sprite_render_runtime.py
	.venv/bin/python tests/test_animation.py
	.venv/bin/python tests/test_actor_contract.py
	.venv/bin/python tests/test_contact.py
	.venv/bin/python tests/test_dagger_actor.py
	.venv/bin/python tests/test_dagger_actor_runtime.py
	.venv/bin/python tests/test_damage.py
	.venv/bin/python tests/test_damage_runtime.py
	.venv/bin/python tests/test_weapon_runtime.py
	.venv/bin/python tests/test_zombie.py
	.venv/bin/python tests/test_zombie_runtime.py
	.venv/bin/python tests/test_thrower.py
	.venv/bin/python tests/test_thrower_runtime.py
	.venv/bin/python tests/test_spitter.py
	.venv/bin/python tests/test_spitter_runtime.py
	.venv/bin/python tests/test_missile_contact.py
	.venv/bin/python tests/test_missile_runtime.py
	.venv/bin/python tests/test_projectile_edges.py
	.venv/bin/python tests/test_projectile_edge_runtime.py
	.venv/bin/python tests/test_boss_layers.py
	.venv/bin/python tests/test_boss_motion.py
	.venv/bin/python tests/test_boss_motion.py --upper
	.venv/bin/python tests/test_boss_layers_runtime.py
	.venv/bin/python tests/test_boss_upper_runtime.py
	.venv/bin/python tests/test_stone_runtime.py
	.venv/bin/python tests/test_boulder.py
	.venv/bin/python tests/test_boulder_runtime.py
	.venv/bin/python tests/test_pair.py
	.venv/bin/python tests/test_pair_runtime.py
	.venv/bin/python tests/test_wisp.py
	.venv/bin/python tests/test_wisp_runtime.py
	.venv/bin/python tests/test_emerge.py
	.venv/bin/python tests/test_emerge_runtime.py
	.venv/bin/python tests/test_checkpoint.py
	.venv/bin/python tests/test_checkpoint_runtime.py
	.venv/bin/python tests/test_progress.py
	.venv/bin/python tests/test_progress_runtime.py
	.venv/bin/python tests/test_restart_runtime.py
	.venv/bin/python tests/test_status.py
	.venv/bin/python tests/test_wave.py
	.venv/bin/python tests/test_flailer.py
	.venv/bin/python tests/test_flailer_weapon.py
	.venv/bin/python tests/test_flailer_runtime.py
	.venv/bin/python tests/test_large_contact.py
	.venv/bin/python tests/test_dragon_wave.py
	.venv/bin/python tests/test_dragon_shot.py
	.venv/bin/python tests/test_dragon_contact.py
	.venv/bin/python tests/test_dragon_runtime.py
	.venv/bin/python tests/test_dragon.py
	.venv/bin/python tests/test_waveboss.py
	.venv/bin/python tests/test_waveboss_seed.py
	.venv/bin/python tests/test_waveboss_runtime.py
	.venv/bin/python tests/test_eruption.py
	.venv/bin/python tests/test_eruption_runtime.py
	.venv/bin/python tests/test_teleporter.py
	.venv/bin/python tests/test_teleporter_runtime.py
	.venv/bin/python tests/test_hunter.py
	.venv/bin/python tests/test_hunter_shell.py
	.venv/bin/python tests/test_hunter_runtime.py
	.venv/bin/python tests/test_reinforcement_body.py
	.venv/bin/python tests/test_reinforcement_shot.py
	.venv/bin/python tests/test_reinforcement_body_runtime.py
	.venv/bin/python tests/test_edge_actor.py
	.venv/bin/python tests/test_edge_shot.py
	.venv/bin/python tests/test_edge_actor_runtime.py
	.venv/bin/python tests/test_edge_spawn.py
	.venv/bin/python tests/test_edge_spawn_runtime.py
	.venv/bin/python tests/test_reinforcement.py
	.venv/bin/python tests/test_reinforcement_runtime.py
	.venv/bin/python tests/test_crawler.py
	.venv/bin/python tests/test_crawler_runtime.py
	.venv/bin/python tests/test_statue.py
	.venv/bin/python tests/test_statue_shell.py
	.venv/bin/python tests/test_statue_runtime.py
	.venv/bin/python tests/test_shop.py
	.venv/bin/python tests/test_shop_runtime.py
	.venv/bin/python tests/test_container_trap.py
	.venv/bin/python tests/test_container_open_runtime.py
	.venv/bin/python tests/test_container_contact.py
	.venv/bin/python tests/test_container.py
	.venv/bin/python tests/test_container_runtime.py
	.venv/bin/python tests/test_pickup.py
	.venv/bin/python tests/test_pickup_runtime.py
	.venv/bin/python tests/test_screen_attack_runtime.py
	.venv/bin/python tests/test_hazard.py
	.venv/bin/python tests/test_hazard_runtime.py
	.venv/bin/python tests/test_sentry.py
	.venv/bin/python tests/test_sentry_runtime.py
	.venv/bin/python tests/test_loot.py
	.venv/bin/python tests/test_loot_runtime.py
	.venv/bin/python tests/test_actor_motion.py
	.venv/bin/python tests/test_actor_motion_runtime.py
	.venv/bin/python tests/test_skeleton.py
	.venv/bin/python tests/test_skeleton_runtime.py
	.venv/bin/python tests/test_world.py
	.venv/bin/python tests/test_hidden_runtime.py
	.venv/bin/python tests/test_npc_sequence.py
	.venv/bin/python tests/test_npc_runtime.py
clean:
	$(MAKE) -f $(GDK)/makefile.gen JAVA=$(JAVA) clean
