#ifndef ACTOR_DISPATCH_H
#define ACTOR_DISPATCH_H
#include "animation.h"
enum {DRAW_FALLBACK,DRAW_PIECE,DRAW_BODY,DRAW_DRAGON,DRAW_WAVE};
enum {BEHAVIOR_NORMAL,BEHAVIOR_EDGE,BEHAVIOR_REINFORCEMENT,BEHAVIOR_FLAILER,BEHAVIOR_WAVEBOSS,BEHAVIOR_ERUPTION,BEHAVIOR_TELEPORTER,BEHAVIOR_HUNTER,BEHAVIOR_CRAWLER,BEHAVIOR_STATUE,BEHAVIOR_BOULDER,BEHAVIOR_STONE,BEHAVIOR_ZOMBIE,BEHAVIOR_WISP,BEHAVIOR_EMERGE,BEHAVIOR_HAZARD};
typedef struct {const AnimFrame *(*frame)(u16 slot);u16 layout,behavior;} ActorDispatch;
extern const ActorDispatch actor_dispatch[];
typedef u8 (*ActorVulnerable)(u16 slot);
extern const ActorVulnerable actor_vulnerable[];
#endif
