"""Precompute the cave border sprite geometry without changing its pixels."""
from pathlib import Path
rows=[]
for offset in range(32):
 row=[]
 for i in range(9):
  x=i*32-offset
  if x>=248:row.append('{0,0,0,0}');continue
  skip=max(0,-x//8);width=4-skip;x+=skip*8
  if x+width*8>248:width=(248-x+7)//8
  row.append('{%d,%d,%d,%d}'%(x+128,(width-1)*4,(width+1)//2,(i*4+skip)&31))
 rows.append('{'+','.join(row)+'}')
Path('src/cave_sprite_geometry.inc').write_text('/* Horizontal geometry for each sub-tile offset; generated by tools/build_cave_geometry.py. */\nstatic const struct {u16 x;u8 size,units,column;} cave_geometry[32][9]={\n'+',\n'.join(rows)+'\n};\n')
