"""Compile the witnessed arcade title and native HUD into Genesis tiles."""
import hashlib,json
import numpy as np
from PIL import Image
from arcade_source import Source,ROOT
from extract import decode,pack
source=Source();board=json.loads((ROOT/'assets/board.json').read_text())
path=ROOT/'assets/ui/title_arcade.png';rgb=np.asarray(Image.open(path).convert('RGB'))
assert rgb.shape==(224,256,3)
# Genesis RGB333, with the original logo geometry unchanged.
colors=(rgb.astype(np.uint16)//32);words=colors[:,:,0]*2+colors[:,:,1]*32+colors[:,:,2]*512
words=words.copy();words[128:200]=0
# Footer: original copyright on row 25, blank row 26, creator on row 27.
words[200:208,:248]=words[208:216,8:].copy();words[208:224]=0
sets=[]
for y in range(0,224,8):
 for x in range(0,256,8):sets.append(frozenset(map(int,words[y:y+8,x:x+8].flat))|{0})
palettes=[]
for colorset in sorted(set(sets),key=lambda s:(-len(s),tuple(sorted(s)))):
 choices=[(len(p|colorset),i) for i,p in enumerate(palettes) if len(p|colorset)<=16]
 if choices:palettes[min(choices)[1]]|=colorset
 else:palettes.append(set(colorset))
assert len(palettes)<=4,len(palettes)
palettes=[[0]+sorted(p-{0}) for p in palettes]
while len(palettes)<4:palettes.append([0])
reserved=[0,0x002,0xeee,0x00e,0x08e,0x444]
last=reserved+sorted(set(palettes[3])-set(reserved))
assert len(last)<=15
palettes[3]=last+[0]*(15-len(last))+[0xeee]
palette=[]
for p in palettes:palette+=p+[0]*(16-len(p))
tiles=[];lookup={};mapping=[]
for y in range(0,224,8):
 for x in range(0,256,8):
  block=words[y:y+8,x:x+8];cset=set(map(int,block.flat));bank=next(i for i,p in enumerate(palettes) if cset<=set(p));p=palettes[bank]
  raw=pack(np.array([[p.index(int(w)) for w in row] for row in block]))
  if raw not in lookup:lookup[raw]=len(tiles);tiles.append(raw)
  mapping.append(16+lookup[raw]+(bank<<13))
assert len(tiles)<1000
chars=decode(b''.join(source.files[f['path']] for f in board['regions']['chars']['files']),board['layouts']['characters'])
# Original 8x8 character lettering; source numeral tiles are 0..9.
font=[]
for code in range(32,128):
 n=code-48 if 48<=code<=57 else code
 font.append(pack(np.array([1,15,3,0],dtype=np.uint8)[chars[n]]))
# Nine HUD tiles in slots 7..15, outside all terrain/sprite/dialogue caches.
icons=[]
for n in range(9):
 a=np.ones((8,8),dtype=np.uint8)
 if n<3:
  a[1:7,1:7]=6;a[2:6,2:6]=15 if n==0 else 1 if n==1 else 6
 elif n==3:a[7,:]=15
 else:
  shapes=['00111000/01111100/11111110/11111110/01111100/00111000/00010000/00000000',
          '01111100/01010100/01111100/00111000/00111000/00010000/00000000/00000000',
          '00001100/00011100/00111000/01110000/00100000/01010000/10000000/00000000',
          '00111000/01111100/00111000/01111100/11111110/10111010/00101000/01101100',
          '00011000/00111100/00011000/00111100/01111110/01111110/00111100/00000000']
  a=np.array([[15 if c=='1' else 1 for c in row] for row in shapes[n-4].split('/')],dtype=np.uint8)
 icons.append(pack(a))
def array(name,typ,values):return f'static const {typ} {name}[]={{'+','.join(values)+'};\n'
def binary(name,data):return array(name,'u32',[f'0x{int.from_bytes(data[i:i+4],"big"):08x}' for i in range(0,len(data),4)])
out='/* Generated by tools/build_ui.py; original arcade artwork, RGB333. */\n'
out+=f'#define TITLE_TILE_COUNT {len(tiles)}\n'
out+=binary('title_tiles',b''.join(tiles))+array('title_map','u16',map(str,mapping))+array('title_palette','u16',map(str,palette))
out+=binary('title_font',b''.join(font))+binary('hud_icons',b''.join(icons))
hudfont=b''.join(pack(np.array([1,15,1,1],dtype=np.uint8)[chars[code-48 if 48<=code<=57 else code]]) for code in range(32,128))
out+=binary('hud_font',hudfont)
(ROOT/'src/ui_data.inc').write_text(out)
report=dict(source_set=source.lock['aggregate_sha256'],source_png_sha256=hashlib.sha256(path.read_bytes()).hexdigest(),source_frame=600,tiles=len(tiles),palette_lines=len(palettes),scope='Original arcade title pixels and source character font; RGB444 to RGB333 reduction only. Menu region replaces GAME OVER/INSERT COIN; native mode menus and credit display are separate.')
(ROOT/'reference/title_graphics.json').write_text(json.dumps(report,indent=2)+'\n')
print(report)

# Fixed 24B2 selects this source difficulty/weapon damage table.
source.expect(None,0x24d4,'21f0b6')
(ROOT/'src/difficulty_data.inc').write_text('/* Source bank 6 B6F0, eight difficulty rows, five weapon tiers. */\nstatic const u8 difficulty_damage[8][5]={'+','.join('{'+','.join(map(str,source.read(6,0xb6f0+i*5,5)))+'}' for i in range(8))+'};\n')
