"""Compile the witnessed arcade title and native HUD into Genesis tiles."""
import hashlib,json
import numpy as np
from PIL import Image
from arcade_source import Source,ROOT
from extract import decode,pack
source=Source();board=json.loads((ROOT/'assets/board.json').read_text())
path=ROOT/'assets/ui/title_arcade.png';rgb=np.asarray(Image.open(path).convert('RGB'))
assert rgb.shape==(224,256,3)
# Genesis RGB333, with the original logo geometry unchanged.
colors=(rgb.astype(np.uint16)//32);words=colors[:,:,0]*2+colors[:,:,1]*32+colors[:,:,2]*512
words=words.copy();words[128:200]=0
# Restore the original 8-pixel copyright lettering without resampling.
footer=words[208:216,8:].copy()
words[200:224]=0;words[200:208,8:256]=footer
sets=[]
for y in range(0,224,8):
 for x in range(0,256,8):sets.append(frozenset(map(int,words[y:y+8,x:x+8].flat))|{0})
palettes=[]
for colorset in sorted(set(sets),key=lambda s:(-len(s),tuple(sorted(s)))):
 choices=[(len(p|colorset),i) for i,p in enumerate(palettes) if len(p|colorset)<=16]
 if choices:palettes[min(choices)[1]]|=colorset
 else:palettes.append(set(colorset))
assert len(palettes)<=4,len(palettes)
palettes=[[0]+sorted(p-{0}) for p in palettes]
while len(palettes)<4:palettes.append([0])
reserved=[0,0x002,0xeee,0x00e,0x08e,0x444]
last=reserved+sorted(set(palettes[3])-set(reserved))
assert len(last)<=15
palettes[3]=last+[0]*(15-len(last))+[0xeee]
palette=[]
for p in palettes:palette+=p+[0]*(16-len(p))
tiles=[];lookup={};mapping=[]
for y in range(0,224,8):
 for x in range(0,256,8):
  block=words[y:y+8,x:x+8];cset=set(map(int,block.flat));bank=next(i for i,p in enumerate(palettes) if cset<=set(p));p=palettes[bank]
  raw=pack(np.array([[p.index(int(w)) for w in row] for row in block]))
  if raw not in lookup:lookup[raw]=len(tiles);tiles.append(raw)
  mapping.append(16+lookup[raw]+(bank<<13))
assert len(tiles)<1000
chars=decode(b''.join(source.files[f['path']] for f in board['regions']['chars']['files']),board['layouts']['characters'])
# Original 8x8 character lettering; source numeral tiles are 0..9.
font=[]
for code in range(32,128):
 n=code-48 if 48<=code<=57 else code
 font.append(pack(np.array([1,15,3,0],dtype=np.uint8)[chars[n]]))
# Nine HUD tiles in slots 7..15, outside all terrain/sprite/dialogue caches.
icons=[]
for n in range(9):
 a=np.ones((8,8),dtype=np.uint8)
 if n<3:
  a[1:7,1:7]=6;a[2:6,2:6]=15 if n==0 else 1 if n==1 else 6
 elif n==3:a[7,:]=15
 else:
  shapes=['00111000/01111100/11111110/11111110/01111100/00111000/00010000/00000000',
          '01111100/01010100/01111100/00111000/00111000/00010000/00000000/00000000',
          '00001100/00011100/00111000/01110000/00100000/01010000/10000000/00000000',
          '00111000/01111100/00111000/01111100/11111110/10111010/00101000/01101100',
          '00011000/00111100/00011000/00111100/01111110/01111110/00111100/00000000']
  a=np.array([[15 if c=='1' else 1 for c in row] for row in shapes[n-4].split('/')],dtype=np.uint8)
 icons.append(pack(a))
def array(name,typ,values):return f'static const {typ} {name}[]={{'+','.join(map(str,values))+'};\n'
def binary(name,data):return array(name,'u32',[f'0x{int.from_bytes(data[i:i+4],"big"):08x}' for i in range(0,len(data),4)])
out='/* Generated by tools/build_ui.py; original arcade artwork, RGB333. */\n'
out+=f'#define TITLE_TILE_COUNT {len(tiles)}\n'
out+=binary('title_tiles',b''.join(tiles))+array('title_map','u16',map(str,mapping))+array('title_palette','u16',map(str,palette))
out+=binary('title_font',b''.join(font))+binary('hud_icons',b''.join(icons))
hudfont=b''.join(pack(np.array([1,15,1,1],dtype=np.uint8)[chars[code-48 if 48<=code<=57 else code]]) for code in range(32,128))
out+=binary('hud_font',hudfont)
# Approved Home-only monogram. Keep the arcade wordmark and all its palettes
# byte-identical: extract the two disconnected MD letters, then map each tile
# into the closest already-existing title palette.
from collections import deque
concept_path=ROOT/'art/black_tiger_md_logo_concept.png'
concept=Image.open(concept_path).convert('RGB')
cut=np.asarray(concept.crop((640,535,1152,792))).copy()
ink=cut.max(axis=2)>48;seen=np.zeros(ink.shape,bool);components=[]
for yy,xx in zip(*np.nonzero(ink)):
 if seen[yy,xx]:continue
 seen[yy,xx]=True;q=deque([(yy,xx)]);component=[]
 while q:
  cy,cx=q.popleft();component.append((cy,cx))
  for dy in (-1,0,1):
   for dx in (-1,0,1):
    ny,nx=cy+dy,cx+dx
    if 0<=ny<ink.shape[0] and 0<=nx<ink.shape[1] and ink[ny,nx] and not seen[ny,nx]:
     seen[ny,nx]=True;q.append((ny,nx))
 components.append(component)
keep=np.zeros(ink.shape,bool)
for component in sorted(components,key=len,reverse=True)[:2]:
 for yy,xx in component:keep[yy,xx]=True
cut[~keep]=0
yy,xx=np.nonzero(keep)
monogram=Image.fromarray(cut).crop((int(xx.min()),int(yy.min()),int(xx.max()+1),int(yy.max()+1)))
md=np.asarray(monogram.resize((64,32),Image.Resampling.BOX)).astype(np.int32)
md_tiles=[];md_map=[];md_preview=np.zeros_like(md,dtype=np.uint8)
colors=np.array([[(w>>1)&7,(w>>5)&7,(w>>9)&7] for w in palette],dtype=np.int32)*255//7
for y in range(0,32,8):
 for x in range(0,64,8):
  block=md[y:y+8,x:x+8];black=block.max(axis=2)<32;choices=[]
  for bank in range(4):
   pal=colors[bank*16:(bank+1)*16]
   distances=((block[:,:,None,:]-pal[None,None,:,:])**2).sum(axis=3)
   indices=distances.argmin(axis=2);indices[black]=0
   error=int(np.take_along_axis(distances,indices[:,:,None],axis=2).sum())
   choices.append((error,bank,indices))
  _,bank,indices=min(choices,key=lambda v:v[0])
  md_map.append((16+len(tiles)+len(md_tiles))|(bank<<13));md_tiles.append(pack(indices.astype(np.uint8)))
  md_preview[y:y+8,x:x+8]=colors[bank*16+indices]
assert 16+len(tiles)+len(md_tiles)<1000
out+=f'#define HOME_MD_TILE_COUNT {len(md_tiles)}\n'
out+=binary('home_md_tiles',b''.join(md_tiles))+array('home_md_map','u16',map(str,md_map))
Image.fromarray(md_preview).save(ROOT/'res/generated/home_md_logo.png')
# Tiny 13x5 v1.1 stamp, independent of the arcade's 8x8 menu font.
version=np.zeros((8,16),np.uint8)
for x,y,rows in [(0,4,['101','101','010']),(4,2,['010','110','010','010','111']),(8,6,['1']),(10,2,['010','110','010','010','111'])]:
 for dy,row in enumerate(rows):
  for dx,bit in enumerate(row):version[y+dy,x+dx]=15 if bit=='1' else 0
out+=binary('title_version_tiles',pack(version[:,:8])+pack(version[:,8:]))
out+=array('title_version_map','u16',[0xe000|16+len(tiles)+len(md_tiles),0xe000|17+len(tiles)+len(md_tiles)])

# User-supplied pixel art: sample the original 16x16 grid, keeping hard edges.
yashichi_path=ROOT/'art/yashichi.png'
yashichi=np.asarray(Image.open(yashichi_path).convert('RGB').crop((16,14,208,206)).resize((16,16),Image.Resampling.NEAREST)).astype(np.int32)
pal=colors[48:64]
distances=((yashichi[:,:,None,:]-pal[None,None,:,:])**2).sum(axis=3)
yashichi_indices=distances.argmin(axis=2).astype(np.uint8)
warm=(yashichi[:,:,0]>yashichi[:,:,2]+40)&(yashichi[:,:,0]>yashichi[:,:,1]*1.15)
yashichi_indices[warm]=np.where(yashichi[:,:,0][warm]>=160,3,6)
yashichi_indices[yashichi.max(axis=2)<48]=0
yashichi_indices=np.pad(np.asarray(Image.fromarray(yashichi_indices).resize((12,12),Image.Resampling.NEAREST)),((2,2),(2,2)))
# Genesis sprite patterns are stored top-to-bottom, then left-to-right.
out+=binary('home_cursor_tiles',b''.join(pack(yashichi_indices[y:y+8,x:x+8]) for x in (0,8) for y in (0,8)))
shop_pal=np.fromfile(ROOT/'res/generated/object_palette.bin',dtype='>u2')[16:]
shop_rgb=np.array([[((int(c)>>shift)&7)*255//7 for shift in (1,5,9)] for c in shop_pal])
shop_indices=1+((pal[yashichi_indices][:,:,None,:]-shop_rgb[None,None,1:,:])**2).sum(3).argmin(2)
shop_indices[yashichi_indices==0]=0
out+=binary('shop_cursor_tiles',b''.join(pack(shop_indices[y:y+8,x:x+8]) for x in (0,8) for y in (0,8)))
Image.fromarray(pal[yashichi_indices].astype(np.uint8)).save(ROOT/'res/generated/home_cursor.png')

(ROOT/'src/ui_data.inc').write_text(out)
report=dict(source_set=source.lock['aggregate_sha256'],source_png_sha256=hashlib.sha256(path.read_bytes()).hexdigest(),source_frame=600,tiles=len(tiles),palette_lines=len(palettes),scope='Original arcade title pixels and source character font; RGB444 to RGB333 reduction only. Menu region replaces GAME OVER/INSERT COIN; native mode menus and credit display are separate.')
report['home_md']={'source_sha256':hashlib.sha256(concept_path.read_bytes()).hexdigest(),'rectangle':[96,104,64,32],'tiles':len(md_tiles),'original_palette_unchanged':True,'home_only':True}
report['menu_font']={'glyph_pixels':[8,8],'advance_pixels':8,'scale':1.0,'requested_scale':1.0,'scope':'Original full-size arcade lettering in all menu options and Capcom/Rester footers; Home, settings, Debug and level selection use two columns.'}
report['home_cursor']={'source_sha256':hashlib.sha256(yashichi_path.read_bytes()).hexdigest(),'pixels':[16,16],'source_grid_crop':[16,14,208,206],'home_only':False,'palette_unchanged':True,'warm_body_color':'red'}
report['version_stamp']={'text':'v1.1','rectangle':[232,216,16,8]}
(ROOT/'reference/title_graphics.json').write_text(json.dumps(report,indent=2)+'\n')
print(report)

# Fixed 24B2 selects this source difficulty/weapon damage table.
source.expect(None,0x24d4,'21f0b6')
(ROOT/'src/difficulty_data.inc').write_text('/* Source bank 6 B6F0, eight difficulty rows, five weapon tiers. */\nstatic const u8 difficulty_damage[8][5]={'+','.join('{'+','.join(map(str,source.read(6,0xb6f0+i*5,5)))+'}' for i in range(8))+'};\n')
