"""Compile the player's three-way dagger volleys into native animation segments."""
from arcade_source import Source,ROOT
from extract_animation import compile_clip
import json
def generate(s):
 segments=[];indices={};pending=[]
 def intern(pc):
  if pc not in indices:indices[pc]=len(segments);segments.append(None);pending.append(pc)
  return indices[pc]
 roots=[intern(pc) for pc in (0xa2f0,0xa2fb,0xa315,0xa32f,0xa33a,0xa354,0xa36e,0xa392)]
 while pending:
  pc=pending.pop(0);clip=compile_clip(s,7,pc);nxt=65535
  for f in clip['frames']:
   vx,vy=s.read(7,f['source_address']+3,2);f['vx']=vx if vx<128 else vx-256;f['vy']=vy if vy<128 else vy-256
  if clip['event']:
   assert clip['event']['address']==0xa271
   nxt=intern(clip['event']['record']+3)
  segments[indices[pc]]=dict(source=pc,clip=clip,next=nxt)
 rows=['/* Generated by tools/extract_player_dagger.py. */']
 for i,seg in enumerate(segments):
  c=seg['clip'];frames=c['frames']
  rows.append('static const AnimFrame dagger_frames_%d[]={%s};'%(i,','.join('{%d,%d,%d,%d,0,%d,%d}'%(f['code'],f['duration'],f['palette'],f['flip'],f['vx'],f['vy']) for f in frames) or '{0}'))
  rows.append('static const AnimClip dagger_clip_%d={dagger_frames_%d,%d,%d};'%(i,i,len(frames),65535 if c['loop'] is None else c['loop']))
 rows.append('static const AnimSegment dagger_segments[]={'+','.join('{&dagger_clip_%d,%d,%d}'%(i,seg['next'],bool(seg['clip']['event'])) for i,seg in enumerate(segments))+'};')
 rows.append('static const u16 dagger_roots[]={'+','.join(map(str,roots))+'};')
 (ROOT/'src/player_dagger_data.inc').write_text('\n'.join(rows)+'\n')
 data=dict(source_set=s.lock['aggregate_sha256'],segments=segments,roots=roots,witnesses=list(s.witnesses.values()))
 (ROOT/'reference/player_dagger.json').write_text(json.dumps(data,indent=2)+'\n');return data
if __name__=='__main__':generate(Source())
